import type { FieldDefinition } from '../types'

export const field: FieldDefinition = {
  key: 'primary_religion',
  labelKey: 'peopleGroups.fields.primary_religion',
  type: 'select',
  category: 'religion',
  tableColumn: true,
  options: [
    { value: 'BOF', labelKey: 'peopleGroups.options.religion.BOF', alternateKeys: ['peopleGroups.options.religionAlternates.buddhist'] },
    { value: 'BMA', labelKey: 'peopleGroups.options.religion.BMA', alternateKeys: ['peopleGroups.options.religionAlternates.buddhist'] },
    { value: 'BTH', labelKey: 'peopleGroups.options.religion.BTH', alternateKeys: ['peopleGroups.options.religionAlternates.buddhist'] },
    { value: 'BLA', labelKey: 'peopleGroups.options.religion.BLA', alternateKeys: ['peopleGroups.options.religionAlternates.buddhist'] },
    { value: 'COR', labelKey: 'peopleGroups.options.religion.COR' },
    { value: 'CFC', labelKey: 'peopleGroups.options.religion.CFC' },
    { value: 'CNP', labelKey: 'peopleGroups.options.religion.CNP' },
    { value: 'CPR', labelKey: 'peopleGroups.options.religion.CPR' },
    { value: 'CRC', labelKey: 'peopleGroups.options.religion.CRC' },
    { value: 'E', labelKey: 'peopleGroups.options.religion.E' },
    { value: 'EAF', labelKey: 'peopleGroups.options.religion.EAF' },
    { value: 'EAW', labelKey: 'peopleGroups.options.religion.EAW' },
    { value: 'EAN', labelKey: 'peopleGroups.options.religion.EAN', alternateKeys: ['peopleGroups.options.religionAlternates.animist'] },
    { value: 'ECF', labelKey: 'peopleGroups.options.religion.ECF' },
    { value: 'ECO', labelKey: 'peopleGroups.options.religion.ECO' },
    { value: 'EDA', labelKey: 'peopleGroups.options.religion.EDA', alternateKeys: ['peopleGroups.options.religionAlternates.daoist', 'peopleGroups.options.religionAlternates.taoist'] },
    { value: 'ENA', labelKey: 'peopleGroups.options.religion.ENA' },
    { value: 'EPO', labelKey: 'peopleGroups.options.religion.EPO', alternateKeys: ['peopleGroups.options.religionAlternates.polytheist'] },
    { value: 'ESA', labelKey: 'peopleGroups.options.religion.ESA' },
    { value: 'ESM', labelKey: 'peopleGroups.options.religion.ESM' },
    { value: 'EJF', labelKey: 'peopleGroups.options.religion.EJF' },
    { value: 'H', labelKey: 'peopleGroups.options.religion.H' },
    { value: 'HOF', labelKey: 'peopleGroups.options.religion.HOF' },
    { value: 'MOF', labelKey: 'peopleGroups.options.religion.MOF', alternateKeys: ['peopleGroups.options.religionAlternates.muslim'] },
    { value: 'MSH', labelKey: 'peopleGroups.options.religion.MSH', alternateKeys: ['peopleGroups.options.religionAlternates.muslim', 'peopleGroups.options.religionAlternates.shiite'] },
    { value: 'MIS', labelKey: 'peopleGroups.options.religion.MIS', alternateKeys: ['peopleGroups.options.religionAlternates.muslim'] },
    { value: 'MSN', labelKey: 'peopleGroups.options.religion.MSN', alternateKeys: ['peopleGroups.options.religionAlternates.muslim'] },
    { value: 'J', labelKey: 'peopleGroups.options.religion.J', alternateKeys: ['peopleGroups.options.religionAlternates.jewish'] },
    { value: 'OBH', labelKey: 'peopleGroups.options.religion.OBH' },
    { value: 'ODZ', labelKey: 'peopleGroups.options.religion.ODZ' },
    { value: 'OJA', labelKey: 'peopleGroups.options.religion.OJA' },
    { value: 'OKI', labelKey: 'peopleGroups.options.religion.OKI' },
    { value: 'OMA', labelKey: 'peopleGroups.options.religion.OMA', alternateKeys: ['peopleGroups.options.religionAlternates.mandaean'] },
    { value: 'OZR', labelKey: 'peopleGroups.options.religion.OZR', alternateKeys: ['peopleGroups.options.religionAlternates.parsi'] },
    { value: 'S', labelKey: 'peopleGroups.options.religion.S' },
    { value: 'N', labelKey: 'peopleGroups.options.religion.N' },
    { value: 'NAG', labelKey: 'peopleGroups.options.religion.NAG' },
    { value: 'NAT', labelKey: 'peopleGroups.options.religion.NAT', alternateKeys: ['peopleGroups.options.religionAlternates.atheist'] },
    { value: 'NSE', labelKey: 'peopleGroups.options.religion.NSE' },
    { value: 'U', labelKey: 'peopleGroups.options.religion.U' }
  ]
}
