import type { FieldDefinition, FieldOption } from '../types'

const options: FieldOption[] = [
  { value: 'C0001', label: 'Aboriginal Australians' },
  { value: 'C0002', label: 'Aceh of Sumatra' },
  { value: 'C0003', label: 'Adamawa-Ubangi' },
  { value: 'C0004', label: 'Adi' },
  { value: 'C0005', label: 'Afar-Saho' },
  { value: 'C0254', label: 'Afro-American, Anglophone' },
  { value: 'C0253', label: 'Afro-American, Hispanic' },
  { value: 'C0337', label: 'Afro-Caribbean' },
  { value: 'C0281', label: 'Agau' },
  { value: 'C0007', label: 'Aimaq' },
  { value: 'C0008', label: 'Albanian' },
  { value: 'C0009', label: 'Altaic' },
  { value: 'C0046', label: 'Amazigh-Kabyle' },
  { value: 'C0047', label: 'Amazigh-Riff' },
  { value: 'C0045', label: 'Amazigh-Saharan' },
  { value: 'C0048', label: 'Amazigh-Shawiya' },
  { value: 'C0049', label: 'Amazigh-Shilha' },
  { value: 'C0010', label: 'Amazon' },
  { value: 'C0011', label: 'Anglo-American' },
  { value: 'C0012', label: 'Anglo-Celt' },
  { value: 'C0318', label: 'Ansari' },
  { value: 'C0237', label: 'Arab World, generic' },
  { value: 'C0013', label: 'Arab, Arabian' },
  { value: 'C0014', label: 'Arab, Hassaniya' },
  { value: 'C0015', label: 'Arab, Levant' },
  { value: 'C0016', label: 'Arab, Libyan' },
  { value: 'C0017', label: 'Arab, Maghreb' },
  { value: 'C0018', label: 'Arab, Shuwa' },
  { value: 'C0019', label: 'Arab, Sudan' },
  { value: 'C0020', label: 'Arab, Yemeni' },
  { value: 'C0319', label: 'Arain' },
  { value: 'C0021', label: 'Armenian' },
  { value: 'C0022', label: 'Assamese' },
  { value: 'C0023', label: 'Assyrian / Aramaic' },
  { value: 'C0024', label: 'Atlantic' },
  { value: 'C0025', label: 'Atlantic-Jola' },
  { value: 'C0026', label: 'Atlantic-Wolof' },
  { value: 'C0027', label: 'Aymara' },
  { value: 'C0028', label: 'Azerbaijani' },
  { value: 'C0029', label: 'Aztec' },
  { value: 'C0298', label: 'Badhai' },
  { value: 'C0030', label: 'Bali-Sasak' },
  { value: 'C0031', label: 'Baloch' },
  { value: 'C0032', label: 'Baltic' },
  { value: 'C0293', label: 'Bania' },
  { value: 'C0033', label: 'Banjar of Kalimantan' },
  { value: 'C0329', label: 'Banjara' },
  { value: 'C0257', label: 'Bantu, Cameroon-Bamileke' },
  { value: 'C0258', label: 'Bantu, Central-Congo' },
  { value: 'C0259', label: 'Bantu, Central-East' },
  { value: 'C0260', label: 'Bantu, Central-Lakes' },
  { value: 'C0261', label: 'Bantu, Central-Luba' },
  { value: 'C0262', label: 'Bantu, Central-South' },
  { value: 'C0263', label: 'Bantu, Central-Southeast' },
  { value: 'C0264', label: 'Bantu, Central-Southwest' },
  { value: 'C0265', label: 'Bantu, Central-Tanzania' },
  { value: 'C0266', label: 'Bantu, Chewa-Sena' },
  { value: 'C0267', label: 'Bantu, East-Coastal' },
  { value: 'C0268', label: 'Bantu, Gikuyu-Kamba' },
  { value: 'C0269', label: 'Bantu, Kongo' },
  { value: 'C0035', label: 'Bantu, Makua-Yao' },
  { value: 'C0270', label: 'Bantu, Nguni' },
  { value: 'C0271', label: 'Bantu, Northwest' },
  { value: 'C0272', label: 'Bantu, Shona' },
  { value: 'C0273', label: 'Bantu, Sotho-Tswana' },
  { value: 'C0274', label: 'Bantu, Southeastern' },
  { value: 'C0275', label: 'Bantu, Swahili' },
  { value: 'C0037', label: 'Barito of Kalimantan' },
  { value: 'C0038', label: 'Basque' },
  { value: 'C0039', label: 'Batak-Nias of Sumatra' },
  { value: 'C0040', label: 'Bedouin, Arabian' },
  { value: 'C0041', label: 'Bedouin, Saharan' },
  { value: 'C0042', label: 'Beja' },
  { value: 'C0340', label: 'Beldar' },
  { value: 'C0043', label: 'Bengali' },
  { value: 'C0044', label: 'Benue' },
  { value: 'C0050', label: 'Bhil' },
  { value: 'C0330', label: 'Bhil' },
  { value: 'C0299', label: 'Bhoi' },
  { value: 'C0051', label: 'Bhojpur-Maithili' },
  { value: 'C0052', label: 'Bhutanese' },
  { value: 'C0053', label: 'Bihari' },
  { value: 'C0059', label: 'Borneo-Kalimantan' },
  { value: 'C0054', label: 'Bouyei' },
  { value: 'C0294', label: 'Brahmin' },
  { value: 'C0055', label: 'Brahui' },
  { value: 'C0056', label: 'Bugi-Makassar of Sulawesi' },
  { value: 'C0057', label: 'Bungku-Bajau' },
  { value: 'C0058', label: 'Burmese' },
  { value: 'C0061', label: 'Caucasus' },
  { value: 'C0165', label: 'Central American Indigenous' },
  { value: 'C0062', label: 'Chadic' },
  { value: 'C0064', label: 'Cham' },
  { value: 'C0284', label: 'Chamar' },
  { value: 'C0065', label: 'Chinese' },
  { value: 'C0066', label: 'Chinese-Hui' },
  { value: 'C0338', label: 'Darzi' },
  { value: 'C0252', label: 'Deaf' },
  { value: 'C0339', label: 'Dhobi' },
  { value: 'C0278', label: 'Domari' },
  { value: 'C0285', label: 'Dusadh' },
  { value: 'C0067', label: 'Egyptian' },
  { value: 'C0068', label: 'Ethio-Semitic' },
  { value: 'C0069', label: 'Fiji' },
  { value: 'C0072', label: 'Filipino Tribal' },
  { value: 'C0070', label: 'Filipino, Central' },
  { value: 'C0071', label: 'Filipino, Muslim' },
  { value: 'C0073', label: 'Finno-Ugric' },
  { value: 'C0074', label: 'Finno-Ugric, Saami' },
  { value: 'C0075', label: 'Flores-Sumba-Alor' },
  { value: 'C0076', label: 'French' },
  { value: 'C0077', label: 'Fulani / Fulbe' },
  { value: 'C0078', label: 'Garo-Tripuri' },
  { value: 'C0079', label: 'Germanic' },
  { value: 'C0331', label: 'Gond' },
  { value: 'C0080', label: 'Gond' },
  { value: 'C0081', label: 'Gorontalo of Sulawesi' },
  { value: 'C0082', label: 'Greek' },
  { value: 'C0083', label: 'Guarani' },
  { value: 'C0084', label: 'Guera-Naba of Chad' },
  { value: 'C0085', label: 'Guinean' },
  { value: 'C0086', label: 'Gujarati' },
  { value: 'C0342', label: 'Gujjar' },
  { value: 'C0087', label: 'Gur' },
  { value: 'C0089', label: 'Hani-Akha' },
  { value: 'C0090', label: 'Hausa' },
  { value: 'C0091', label: 'Hindi' },
  { value: 'C0093', label: 'Hispanic' },
  { value: 'C0094', label: 'Hungarian' },
  { value: 'C0095', label: 'Igbo' },
  { value: 'C0096', label: 'Ijaw' },
  { value: 'C0336', label: 'Indo-Caribbean' },
  { value: 'C0097', label: 'Inuit' },
  { value: 'C0098', label: 'Italian' },
  { value: 'C0099', label: 'Japanese' },
  { value: 'C0100', label: 'Jat' },
  { value: 'C0101', label: 'Jawa' },
  { value: 'C0102', label: 'Jews' },
  { value: 'C0341', label: 'Jogi' },
  { value: 'C0301', label: 'Kahar' },
  { value: 'C0103', label: 'Kaili-Tomini of Sulawesi' },
  { value: 'C0104', label: 'Kanarese' },
  { value: 'C0063', label: 'Kanuri-Saharan' },
  { value: 'C0302', label: 'Kapu' },
  { value: 'C0106', label: 'Karen' },
  { value: 'C0107', label: 'Kashmiri' },
  { value: 'C0303', label: 'Kayastha' },
  { value: 'C0108', label: 'Kazakh' },
  { value: 'C0109', label: 'Khoisan' },
  { value: 'C0111', label: 'Korean' },
  { value: 'C0112', label: 'Kru' },
  { value: 'C0346', label: 'Kshatriya' },
  { value: 'C0332', label: 'Kuki Chin' },
  { value: 'C0304', label: 'Kumhar' },
  { value: 'C0305', label: 'Kunbi' },
  { value: 'C0114', label: 'Kurd' },
  { value: 'C0306', label: 'Kurmi' },
  { value: 'C0110', label: 'Kyrgyz' },
  { value: 'C0115', label: 'Lampung of Sumatra' },
  { value: 'C0116', label: 'Lao' },
  { value: 'C0117', label: 'Li' },
  { value: 'C0118', label: 'Lisu' },
  { value: 'C0251', label: 'Luri-Bakhtiari' },
  { value: 'C0286', label: 'Madiga' },
  { value: 'C0121', label: 'Madura of Java' },
  { value: 'C0308', label: 'Mahratta' },
  { value: 'C0287', label: 'Mala' },
  { value: 'C0122', label: 'Malagasy' },
  { value: 'C0123', label: 'Malay' },
  { value: 'C0124', label: 'Malayali' },
  { value: 'C0309', label: 'Mali' },
  { value: 'C0126', label: 'Malinke' },
  { value: 'C0127', label: 'Malinke-Bambara' },
  { value: 'C0128', label: 'Malinke-Jula' },
  { value: 'C0344', label: 'Mallah' },
  { value: 'C0129', label: 'Maltese' },
  { value: 'C0130', label: 'Maluku-Central' },
  { value: 'C0131', label: 'Maluku-Northern' },
  { value: 'C0132', label: 'Maluku-Southern' },
  { value: 'C0133', label: 'Manchu' },
  { value: 'C0134', label: 'Mande' },
  { value: 'C0347', label: 'Manipuri' },
  { value: 'C0135', label: 'Marathi-Konkani' },
  { value: 'C0136', label: 'Maya' },
  { value: 'C0137', label: 'Melayu of Sumatra' },
  { value: 'C0138', label: 'Miao / Hmong' },
  { value: 'C0139', label: 'Micronesian' },
  { value: 'C0140', label: 'Minahasa-Sangir of Sulawesi' },
  { value: 'C0141', label: 'Minangkabau-Rejang of Sumatra' },
  { value: 'C0142', label: 'Miri-Kachin' },
  { value: 'C0143', label: 'Mixe' },
  { value: 'C0144', label: 'Mixtec' },
  { value: 'C0145', label: 'Mizo' },
  { value: 'C0147', label: 'Mon-Khmer' },
  { value: 'C0146', label: 'Mongolian' },
  { value: 'C0148', label: 'Munda-Santal' },
  { value: 'C0149', label: 'Musi of Sumatra' },
  { value: 'C0310', label: 'Nai' },
  { value: 'C0295', label: 'Nair' },
  { value: 'C0288', label: 'Namasudra' },
  { value: 'C0150', label: 'Nepali-Pahari' },
  { value: 'C0151', label: 'New Caledonia' },
  { value: 'C0152', label: 'New Guinea' },
  { value: 'C0153', label: 'Nilotic' },
  { value: 'C0154', label: 'North American Indigenous' },
  { value: 'C0155', label: 'Nosu' },
  { value: 'C0156', label: 'Nuba Mountains' },
  { value: 'C0157', label: 'Nubian' },
  { value: 'C0158', label: 'Nupe' },
  { value: 'C0159', label: 'Nuristani' },
  { value: 'C0311', label: 'OBC Hindu' },
  { value: 'C0321', label: 'OBC Muslim' },
  { value: 'C0163', label: 'Odia' },
  { value: 'C0160', label: 'Ogan of Sumatra' },
  { value: 'C0161', label: 'Omotic' },
  { value: 'C0164', label: 'Oromo' },
  { value: 'C0343', label: 'Other Backward Class' },
  { value: 'C0289', label: 'Other Dalit' },
  { value: 'C0296', label: 'Other Forward Caste' },
  { value: 'C0168', label: 'Other Hispanic American' },
  { value: 'C0170', label: 'Other Pacific Islanders' },
  { value: 'C0172', label: 'Other South Asian' },
  { value: 'C0326', label: 'Other South Asian' },
  { value: 'C0171', label: 'Other Southeast Asian' },
  { value: 'C0173', label: 'Other Sub-Saharan African' },
  { value: 'C0229', label: 'Other Tibeto-Burmese' },
  { value: 'C0174', label: 'Otomi' },
  { value: 'C0175', label: 'Ouaddai-Fur' },
  { value: 'C0176', label: 'Parsee' },
  { value: 'C0177', label: 'Pasemah of Sumatra' },
  { value: 'C0178', label: 'Pashtun' },
  { value: 'C0290', label: 'Pasi' },
  { value: 'C0179', label: 'Persian' },
  { value: 'C0180', label: 'Polynesian' },
  { value: 'C0181', label: 'Portuguese, Brazilian' },
  { value: 'C0182', label: 'Portuguese, European' },
  { value: 'C0183', label: 'Punjabi' },
  { value: 'C0184', label: 'Pygmy' },
  { value: 'C0185', label: 'Quechua' },
  { value: 'C0186', label: 'Rajasthani' },
  { value: 'C0297', label: 'Rajput' },
  { value: 'C0345', label: 'Rift' },
  { value: 'C0279', label: 'Romani' },
  { value: 'C0187', label: 'Romanian' },
  { value: 'C0189', label: 'Sara-Bagirmi' },
  { value: 'C0324', label: 'Sayyid' },
  { value: 'C0190', label: 'Scandinavian' },
  { value: 'C0191', label: 'Shan' },
  { value: 'C0276', label: 'Sidama' },
  { value: 'C0192', label: 'Sindhi' },
  { value: 'C0193', label: 'Sinhala' },
  { value: 'C0194', label: 'Slav, Eastern' },
  { value: 'C0195', label: 'Slav, Southern' },
  { value: 'C0196', label: 'Slav, Western' },
  { value: 'C0197', label: 'Solomons' },
  { value: 'C0198', label: 'Somali' },
  { value: 'C0312', label: 'Sonar' },
  { value: 'C0199', label: 'Songhai' },
  { value: 'C0200', label: 'Soninke' },
  { value: 'C0201', label: 'South American Indigenous' },
  { value: 'C0282', label: 'South Asian Buddhist' },
  { value: 'C0283', label: 'South Asian Christian' },
  { value: 'C0335', label: 'South Asian Jain' },
  { value: 'C0328', label: 'South Asian Sikh' },
  { value: 'C0333', label: 'South Asian Tribal' },
  { value: 'C0188', label: 'South Himalayan' },
  { value: 'C0202', label: 'Spanish' },
  { value: 'C0248', label: 'Sub-Saharan African, generic' },
  { value: 'C0203', label: 'Sudanic' },
  { value: 'C0204', label: 'Sunda-Betawi of Java' },
  { value: 'C0205', label: 'Susu' },
  { value: 'C0280', label: 'Swiss' },
  { value: 'C0207', label: 'Tai' },
  { value: 'C0210', label: 'Taiwan Indigenous' },
  { value: 'C0211', label: 'Tajik' },
  { value: 'C0212', label: 'Talysh' },
  { value: 'C0213', label: 'Tamil' },
  { value: 'C0334', label: 'Tangsa Naga' },
  { value: 'C0313', label: 'Teli' },
  { value: 'C0214', label: 'Telugu' },
  { value: 'C0215', label: 'Thai' },
  { value: 'C0216', label: 'Tibetan' },
  { value: 'C0217', label: 'Timor' },
  { value: 'C0218', label: 'Toraja of Sulawesi' },
  { value: 'C0219', label: 'Tuareg' },
  { value: 'C0220', label: 'Tukangbesi of Sulawesi' },
  { value: 'C0221', label: 'Turkic' },
  { value: 'C0222', label: 'Turkmen' },
  { value: 'C0223', label: 'Ural-Siberian' },
  { value: 'C0224', label: 'Urdu' },
  { value: 'C0225', label: 'Uyghur' },
  { value: 'C0226', label: 'Uzbek' },
  { value: 'C0292', label: 'Valmiki' },
  { value: 'C0315', label: 'Vanniyan' },
  { value: 'C0227', label: 'Vanuatu' },
  { value: 'C0228', label: 'Vietnamese' },
  { value: 'C0316', label: 'Viswakarma' },
  { value: 'C0314', label: 'Vokkaliga' },
  { value: 'C0230', label: 'West Malaysia Indigenous' },
  { value: 'C0317', label: 'Yadav' },
  { value: 'C0232', label: 'Yao-Mien' },
  { value: 'C0233', label: 'Yoruba' },
  { value: 'C0234', label: 'Zapotec' },
  { value: 'C0235', label: 'Zhuang' }
]

export const field: FieldDefinition = {
  key: 'imb_reg_of_people_2',
  labelKey: 'peopleGroups.fields.imb_reg_of_people_2',
  type: 'select',
  category: 'rop',
  options
}
